### ISSUE TITLE
Exception caught is not handled

### ISSUE THREAD

**Issue by vairamsvsjdo** [ORF-4450/RobotLib#7]
https://github.com/ORF-4450/RobotLib/commit/e152e2a076fb16a591b5123665bc5e368629bf62#r31868005

**Comment by Crossle86** [comment]
If that function fails, it has no effect on the operation of the robot, and since we always want to keep running, we ignore the  exception and use the default values for the version info fields. This exception catch should log the exception so we know it happened and the function will be updated to do so.
